name = "Test"
uuid = "6b83d48c-b37c-4565-8a9c-f1a0fb121951"
authors = ["Ben Ide <ben@bencide.com>"]
version = "0.1.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
